name: jenbarrowsphotography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.59715
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0704'
    - '#d5d8df'
    - '#4f4034'
    - '#7c6865'
    - '#a19595'
  brandStrength: 0.46483960933983326
  lightness: 0.375
  saturation: 0.5794261351693422
  rhythmicContrast: 0.9985663406550884
purpose: []
