name: jenbarrowsphotography
favicon: null
layout_spectrum: 0.3774616648443043
typography_spectrum: 0.7810637129005045
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.46483960933983326
  lightness: 0.07257771957665682
  saturation: 0.5794261351693422
  rhythmicContrast: 0.9985663406550884
purpose: []
